services:
  server:
    build: ./Server/thebois-dtu-pay
    container_name: dtu-pay-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - dtu-network

  client:
    build: ./Client/dtu-pay-client
    container_name: dtu-pay-client
    ports:
      - "8181:8181"
    volumes:
      - ./Client/dtu-pay-client/target/surefire-reports:/app/target/surefire-reports
    depends_on:
      server:
        condition: service_healthy
    networks:
      - dtu-network

networks:
  dtu-network:
    driver: bridge