services:
  server:
    build: ./Server/thebois-dtu-pay
    container_name: dtu-pay-server
    ports:
      - "8080:8080"
    # The Healthcheck: Checks if port 8080 is actually accepting connections
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - dtu-network

  client:
    build: ./Client/dtu-pay-client
    container_name: dtu-pay-client
    volumes:
      - ./Client/dtu-pay-client/target/surefire-reports:/app/target/surefire-reports
    depends_on:
      server:
        # This tells the client NOT to start until the server healthcheck passes
        condition: service_healthy
    networks:
      - dtu-network

networks:
  dtu-network:
    driver: bridge