services:
  server:
    build: ./Server/thebois-dtu-pay
    container_name: dtu-pay-server
    environment:
      - QUARKUS_HTTP_HOST=0.0.0.0
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080"]
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 3s
    networks:
      - dtu-network

  client:
    build: ./Client/dtu-pay-client
    container_name: dtu-pay-client
    ports:
      - "8181:8181"
    volumes:
      - ./Client/dtu-pay-client/target/surefire-reports:/app/target/surefire-reports
    depends_on:
      server:
        condition: service_healthy
    networks:
      - dtu-network

networks:
  dtu-network:
    driver: bridge