version: '3.8'

services:
  dtu-pay-server:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_HTTP_HOST=0.0.0.0
    volumes:
      - ./customers.json:/deployments/customers.json
